// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCN5VAk-Iy1NGTZsXm55V9pxfNs1izTXWw',
    appId: '1:641466964180:android:486d6bd5b6b453581b4341',
    messagingSenderId: '641466964180',
    projectId: 'knowpedia-df445',
    databaseURL: 'https://knowpedia-df445-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'knowpedia-df445.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBk0444J1csn1W9ONwokB_dGjWhC5308sc',
    appId: '1:641466964180:ios:232c1e09909ae6d51b4341',
    messagingSenderId: '641466964180',
    projectId: 'knowpedia-df445',
    databaseURL: 'https://knowpedia-df445-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'knowpedia-df445.appspot.com',
    iosClientId: '641466964180-dn7tj1tvgsdmsju1dcck3tmbqaca7f4o.apps.googleusercontent.com',
    iosBundleId: 'com.example.knowpedia',
  );
}
